---

- name: "[Fedora] Install dependencies"
  become_user: root
  dnf:
    name:
      - util-linux-user
      - zsh
    state: latest
  when: ansible_distribution == 'Fedora'

# - debug: var=installation

- name: "Cloning oh-my-zsh"
  become_user: "{{ user }}"
  git:
    repo=https://github.com/ohmyzsh/ohmyzsh
    dest=~/.oh-my-zsh

- name: "Cloning zsh auto suggestions"
  become_user: "{{ user }}"
  git:
    repo=https://github.com/zsh-users/zsh-autosuggestions
    dest=~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: "Cloning zsh syntax highlighting"
  become_user: "{{ user }}"
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting
    dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: "Make zsh config backups"
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ user }}
    group={{ user }}
    mode=0664
  with_items:
    - { src: '{{ destination }}/.zshrc', dest: '{{ destination }}/.zshrc_{{ ansible_date_time.epoch }}.bak' }
  when: item.src is file

- name: "Copy .zshrc if not exist"
  copy:
    src=files/.zshrc
    dest={{ destination }}
    owner={{ user }}
    group={{ user }}
    mode=0664

- name: "Copy theme"
  copy:
    src=files/themes/lino-gnzh.zsh-theme
    dest={{ destination }}/.oh-my-zsh/custom/themes
    owner={{ user }}
    group={{ user }}
    mode=0664

- name: "Get zsh path"
  command:  which zsh
  register: ohmyzsh_zsh_path

- name: "Set zsh as default shell"
  become_user: root
  user:
    name: "{{ user }}"
    shell: "{{ ohmyzsh_zsh_path.stdout }}"
