---

- name: "[Fedora] Install utils"
  become_user: root
  dnf:
    name:
      - arandr 
      - docker
      - docker-compose
      - fzf 
      - git-cola 
      - htop 
      - mc 
      - ranger 
      - shutter 
      - terminator 
      - the_silver_searcher 
    state: latest
  when: ansible_distribution == 'Fedora'
