---

- name: "[Fedora] Enable Fedora Copr for Hack Fonts"
  become_user: root
  command: "dnf copr enable -y zawertun/hack-fonts"
  when: ansible_distribution == 'Fedora'
  args:
    warn: no

- name: "[Fedora] Install fonts"
  become_user: root
  dnf:
    name:
      - hack-fonts
    state: latest
  when: ansible_distribution == 'Fedora'
