---

- name: "[Fedora] Enable Fedora Copr for Hack Fonts"
  become_user: root
  command: "dnf copr enable -y zawertun/hack-fonts"
  when: ansible_distribution == 'Fedora'
  args:
    warn: no

- name: "[Fedora] Install fonts"
  become_user: root
  dnf:
    name:
      - hack-fonts
    state: latest
  when: ansible_distribution == 'Fedora'

- name: "Copy DejaVu font"
  copy:
    src=files/DejaVu_Sans_Mono_for_Powerline_Nerd_Font_Complete.otf
    dest={{ destination }}/.local/share/fonts/
    owner={{ user }}
    group={{ user }}
    mode=0664
