---

- name: "[Fedora] Enable Fedora Copr for NeoVim"
  become_user: root
  command: "dnf copr enable -y agriffis/neovim-nightly"
  when: ansible_distribution == 'Fedora'
  args:
    warn: no

- name: "[Fedora] Install NeoVim"
  become_user: root
  dnf:
    name:
      - neovim
    state: latest
  when: ansible_distribution == 'Fedora'

- name: "Copy nvim configs"
  copy:
    src=files/nvim
    dest={{ destination }}/.config
    owner={{ user }}
    group={{ user }}
    mode=0664

- name: "Install Plug for Neovim"
  command: "curl -fLo {{ destination }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  args:
    warn: no

- name: "Install NeoVim Plugins"
  shell: nvim +PlugInstall +UpdateRemotePlugins +qall! --headless
