---

- name: "[Fedora] Enable Fedora Copr for NeoVim"
  become_user: root
  command: "dnf copr enable -y agriffis/neovim-nightly"
  when: ansible_distribution == 'Fedora'

- name: "[Fedora] Install NeoVim & dependencies"
  become_user: root
  dnf:
    name:
      - ack
      - neovim
    state: latest
  when: ansible_distribution == 'Fedora'

- name: "Install pip dependencies"
  pip:
    name:
      - pynvim
    extra_args: --user

- name: "Make nvim backups"
  copy:
    src={{ item.src }}
    dest={{ item.dest }}
    owner={{ user }}
    group={{ user }}
    mode=0664
  with_items:
    - { src: '{{ destination }}/.config/nvim/init.vim', dest: '{{ destination }}/.config/nvim/init_{{ ansible_date_time.epoch }}.vim.bak' }
    - { src: '{{ destination }}/.config/nvim/.ctags', dest: '{{ destination }}/.config/nvim/.ctags_{{ ansible_date_time.epoch }}.bak' }
  when: item.src is file

- name: "Copy nvim configs"
  copy:
    src=files/nvim
    dest={{ destination }}/.config
    owner={{ user }}
    group={{ user }}
    mode=0664

- name: "Install Plug for Neovim"
  command: "curl -fLo {{ destination }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

- name: "Install NeoVim Plugins"
  shell: nvim +PlugInstall +UpdateRemotePlugins +qall! --headless
